### ISSUE TITLE
Update to 'subl' shortcut set-up for El Capitan

### ISSUE THREAD

**Issue by sjschmidt44** [codefellows/code-201-prework#1]
For users that have installed mac OSX El Capitan, they will need to enter a slightly different command:

SUBLIME TEXT 2 users run this:

`ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/sublime /usr/local/bin/subl`
OR

SUBLIME TEXT 3 users run this:

`ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl`

**Comment by SushiTigar** [comment]
Fixed.
