### ISSUE TITLE
WSL User Profile

### ISSUE THREAD

**Issue by dahlbyk** [codefellows/code-201-prework#105]
Students are struggling with the `wr/cdwr` instructions:

https://github.com/codefellows/code-201-prework/blob/b934def3a1e6e7c32f6479d063b2394469b7e1e3/prework/windows/04_updating_terminal.md#L75-L90

Might be better to use [`WSLENV`](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/) to have `%USERPROFILE%` automatically shared from the Windows side, i.e. `setx WSLENV USERPROFILE/up`.

![image](https://user-images.githubusercontent.com/133987/74263422-60d38f80-4cc4-11ea-8cf7-f776b659b8b8.png)

Also, pedantically I'd suggest `cdwh` for `cd` Windows **Home**, not Root.

**Comment by bradsmialek** [comment]
@dahlbyk  Just curious what problems specifically students are having?  I can add or provide clarity around the issue based on this feedback.  Thanks!

**Comment by bradsmialek** [comment]
@dahlbyk Added some clarification  PR #106

**Comment by dahlbyk** [comment]
Both students typed the wrong Windows username and didn't know how to get back to fix it. Removing the "make sure you edit this" dependency via the existing environment variable should be easier.

While we're discussing WSL, how are your students handling GitHub credentials? A simplified version of https://blog.anaisbetts.org/using-github-credentials-in-wsl2/ might be a good idea.

**Comment by bradsmialek** [comment]
credentials run; 
git config --global credential.helper store   followed by push or pull...  enter credentials and the following push/pull should not ask.

**Comment by bradsmialek** [comment]
> Removing the "make sure you edit this" dependency via the existing environment variable should be easier.
> 
@dahlbyk Thank you for the suggestion by the way.  Have any students implemented this yet?

**Comment by dahlbyk** [comment]
> Have any students implemented this yet?

We got them all fixed up manually, then I went looking for a better solution.

> credentials run;
> `git config --global credential.helper store`
> followed by push or pull... enter credentials and the following push/pull should not ask.

Does this work for folks that use 2FA? I try to use teaching as a mini soap box on the importance of account security. 😁

**Comment by brookr** [comment]
I believe this is resolved under our WSL2 setup instructions. If not, please open a new issue in https://github.com/codefellows/setup-guide .
