### ISSUE TITLE
WSL npm Syntax Error

### ISSUE THREAD

**Issue by dahlbyk** [codefellows/code-201-prework#108]
Couple students this week have run into this in Ubuntu (referencing the Windows installation of npm):

```text
npm --version
: not foundram Files/nodejs/npm: 3:
: not foundram Files/nodejs/npm: 5:
/mnt/c/Program Files/nodejs/npm: 6: Syntax error: word unexpected (expecting "in")
```

Can installation guide be modified to avoid this?

cc @codefellows/deltav

**Comment by dahlbyk** [comment]
This appears to only occur when installing on WSL after installing on Windows; uninstalling on Windows and reinstalling on Ubuntu has been the fix. Have not confirmed for myself, though.

**Comment by Calamity-Jaymi** [comment]
I am not enrolled in 201 yet, I start on August 31st. But I have been working on the pre-work this last month and had this same issue, After two long days of trial and error, upgrading to WSL2 and doing the following worked for me.

install latest npm command, and call 
nvm install node
sudo apt-get install -y npm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
((close ubuntu and reopen))
nvm
nvm install node

I hope this works for someone else as well.

**Comment by brookr** [comment]
NVM and npm installation instructions have been updated for WSL2 here: https://github.com/codefellows/setup-guide

Please open an issue there if this problem persists. Thanks for the reports!
