### ISSUE TITLE
Add instructions to set Sublime Text as default git editor

### ISSUE THREAD

**Issue by jonathanstallings** [codefellows/code-201-prework#2]
## Problem
Students are often confused when git drops them into Vim to edit a commit message.

## Proposal
Add instruction to the Git setup portion of the prework to set Sublime (or Atom) as default text editor.

* Relevant part of prework (mac version): https://github.com/codefellows/code-201-prework/blob/master/prework/mac/4_git.md#git-config
* Example Git instructions: https://help.github.com/articles/associating-text-editors-with-git/#using-atom-as-your-editor

**Comment by samhamm** [comment]
Actually, now that we're going Atom, that needs to be changed in here, too...

**Comment by jonathanstallings** [comment]
Changed link to Atom-Git marriage instructions.

**Comment by SushiTigar** [comment]
Is this different than the subl section https://github.com/codefellows/code-201-prework/blob/master/prework/mac/3_sublime_text.md#subl ?

Yes this will be updated to Atom.
