### ISSUE TITLE
Include Codecademy code tutorials links in this document?

### ISSUE THREAD

**Issue by samhamm** [codefellows/code-201-prework#3]
https://www.codefellows.org/courses/code-201/foundations-of-software-development directs students to this repo for prework, and the Codecademy tutorials are not listed here. We should probably have a link to those here so that students are getting consistent guidance as to what the prework for the course actually is. Those items are published in Canvas assignments, but it seems like a lot of students are not even connected with Canvas yet, either.

They may think that coming here constitutes all of the prework.

Putting the Codecademy prework here would be a redundant means of getting the message out to do that prework.

My next 201 starts tomorrow, and at this point, only 3-4 of 14 students have completed the prework.

**Comment by SushiTigar** [comment]
The codecademy tutorials are linked on the codefellows.org page as well as featured as #6 on the README file here.
