### ISSUE TITLE
Some instructions look like commands to type in

### ISSUE THREAD

**Issue by brookr** [codefellows/code-201-prework#56]
for example, a student who tries to run:
`const cowsay = require('cowsay')`
in bash will get an error. 

As seen in: https://github.com/codefellows/code-201-prework/blob/173b9916b8e71f510d204c0f7ff612b7fc062897/prework/windows/06_final_steps.md

**Comment by samhamm** [comment]
Simplify and reword the instructions in the "cowsay" vicinity (NPM section).
