### ISSUE TITLE
Linux tutorial broken

### ISSUE THREAD

**Issue by samhamm** [codefellows/code-201-prework#58]
http://linuxtutorial.todolistme.net/

So... we have to find another one.

**Comment by sjschmidt44** [comment]
This is the tutorial you use, right?https://ryanstutorials.net/linuxtutorial/
          
            
            On Aug 7 2018, at 4:53 pm, Sam Hamm <notifications@github.com> wrote:
            
            
              http://linuxtutorial.todolistme.net/
So... we have to find another one.

**Comment by samhamm** [comment]
Needs to be updated in prework as noted above
