### ISSUE TITLE
npm global install path sucks

### ISSUE THREAD

**Issue by mnfmnfm** [codefellows/code-201-prework#60]

**Comment by samhamm** [comment]
@mnfmnfm, clarify?

**Comment by mnfmnfm** [comment]
\<sarcasm>
you mean this isn't self-explanatory?
\</sarcasm>
Many students, on many OS's, have had the experience that `npm i -g` puts something in a global install location that is not on their PATH, so they can't actually run the installed program. Especially if we move `live-server` installation to prework, we should ensure that we give links to StackOverflow etc. on how to change the npm global install path to something on the PATH.

**Comment by samhamm** [comment]
Ah, gotcha.

**Comment by michaeltreat** [comment]
I have an older doc in the prework stuff that walks through adding stuff to the PATH on Windows. You might be able to scrap some of that. Here's the link https://github.com/codefellows/code-201-prework/blob/master/prework/old.windows/4_install_tree.md

**Comment by mnfmnfm** [comment]
Has been updated for WSL, and have seen this less on Macs in the last month. Closing.
