### ISSUE TITLE
Remove prototypes, inheritance, and .call() from prework

### ISSUE THREAD

**Issue by stephanielingwood** [codefellows/code-201-prework#64]
Khan Academy currently includes prototypes, inheritance, .call() and Object.create() concepts in the JavaScript module. 

The "Object-oriented Design" module at the end has 3 challenges. The concepts in these challenges are:

- Double Rainbow: creating and using constructor functions
- Smiley Face: constructor functions, methods on the prototype
- Flower Grower: prototypes; inheritance using .call() and Object.create() (note: this is not the way we teach inheritance, from what I remember)

I propose that we either:

- stop requiring completion of Smiley Face and Flower Grower, or 
- find another tutorial (which would require redesign of 102)

**Comment by samhamm** [comment]
Sam will implement Stephanie's suggestions and make a PR.
