### ISSUE TITLE
Git download

### ISSUE THREAD

**Issue by sarkis74** [codefellows/code-201-prework#65]
I installed VSC per instructions on Michael Treat video. I than followed instructions for Git download and when I get to select editor it won't let me select VSC. Instead it asks me to download VSC again. Any suggestions?

**Comment by michaeltreat** [comment]
@sarkis74 I took a look, but didn't see anything different. If for some reason it doesn't work, you can always type this command into your command line to associate git with VSC. It does the same thing as if you had the option to select VSC.

``` 
git config --global core.editor "atom --wait"
```

**Comment by samhamm** [comment]
Not a problem.
