### ISSUE TITLE
Merge main WSL guide updates with prework guide?

### ISSUE THREAD

**Issue by michaeltreat** [codefellows/code-201-prework#76]
I'll be updating the hosted version of the [WSL guide](https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide) over the next month. Some of that includes adding a checklist to the main page ( thanks for the idea @johncokos) as well as some simplifications, clarifications, and updates to things like how npm global and local paths work with WSL, and merging any changes from this prework version into the main version as appropriate so they are consistent.

I wanted to get some feedback though to see if there are things we would like removed or added into it. If there are any areas that you've seen students struggle with too I'd like to try and address it all in one go. I'm also curious about how students in other courses such as .NET, Java, and Python are doing with this guide, or if they are even using it at all. 

Thanks!

**Comment by samhamm** [comment]
I'll endeavor to get our folks to read over these materials and cross-reference against what we have in place. In particular, @mnfmnfm could provide excellent insight and review at such a time she has bandwidth to do so. But she is early in a Java 401 at the moment, so we'll see.

**Comment by mnfmnfm** [comment]
We're using this guide in Java! Agreed that npm pathing issues are the biggest pain point right now. For Java we've got a couple of other one-off aliases set up, but nothing major that needs to be reconfigured.

**Comment by michaeltreat** [comment]
Awesome, I'm glad to hear it's able to be used in other 401's.

I know NPM is a bit of an issue, so I'll create a separate issue and share my current solution for it now instead of waiting until an update is ready. Please let me know if there are other issues with NPM that this doesn't cover! Thanks :)

**Comment by michaeltreat** [comment]
@samhamm @mnfmnfm I will be making a PR sometime in the next 2 weeks! The hosted version of the guide will be updated this weekend, and I will then translate that over into a CF-specific guide.

Some of the things I will be doing:

1. Moving and/or Removing sections like the eslint config and other too/non specific sections.
- Initially I added these sections to help ensure the first couple cycles of students had the same setup experiences. This way as students began to graduate and turned to TAs they could all be on the same page. Now that this has been out a while, I am going to attempt to keep it more consistent with the Linux and Mac setups. For specific things like eslint configs, leaving them here is unmaintainable and it may be better to have a master config file, or to just set them up altogether per cohort.

2. Adding CF Specific language vs General Language. 
- Initially I tried to keep this as consistent with my own hosted guide for the same reasons as above, but now that this feels more established, I would like to separate the two guides, and allow this one to become focused much more on the students who will be reading it. This means trimming out some excessive details, creating more CF-centric nomenclature, and creating a more consistent setup with the Mac and Linux setups. If students want to learn more, they can always visit the open-sourced guide I have hosted.

3. Major NPM overhaul. 
- This section is confusing, but once you understand it then it really does make perfect sense. However, that can be a somewhat steep learning curve for brand new students, As such, I will need to re-vamp this section and make this much, much more clear.

4. Incorporating all of the additions and changes that have been made to this guide since it was introduced into the pre-work.
5. Creating more visuals to help paint the concepts in student's minds.
6. Adding more videos specific to course-levels.
7. Adding a checklist for students to use to track each important item.

Please gather and share any other feedback if you can so I can get it into this newer version! I will also make a strong effort to commit often so you can pick through the history as you like.

Thanks!!

**Comment by samhamm** [comment]
Thanks for the notice on this, and thanks for all of your contributions!

**Comment by mnfmnfm** [comment]
Hey @michaeltreat any updates on this?

**Comment by michaeltreat** [comment]
@mnfmnfm The version I'm hosting is about 70% complete, but Microsoft just released WSL 2.0, so I will need to review that and update the guide again. I am finally getting into the groove here at work so I'm able to start picking up my side projects again. I will try and get a 1st draft update of this over the next month!
